// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Music_App.Models;

#nullable disable

namespace Music_App.Migrations
{
    [DbContext(typeof(MusicContext))]
    [Migration("20251203211544_playlist")]
    partial class playlist
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Music_App.Models.Music", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackId"), 1L, 1);

                    b.Property<string>("TrackArtist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TrackLength")
                        .HasColumnType("float");

                    b.Property<string>("TrackTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrackId");

                    b.ToTable("Musics");
                });

            modelBuilder.Entity("Music_App.Models.Playlist", b =>
                {
                    b.Property<int>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaylistId"), 1L, 1);

                    b.Property<string>("PlaylistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlaylistId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("MusicPlaylist", b =>
                {
                    b.Property<int>("MusicListTrackId")
                        .HasColumnType("int");

                    b.Property<int>("PlaylistsPlaylistId")
                        .HasColumnType("int");

                    b.HasKey("MusicListTrackId", "PlaylistsPlaylistId");

                    b.HasIndex("PlaylistsPlaylistId");

                    b.ToTable("MusicPlaylist");
                });

            modelBuilder.Entity("MusicPlaylist", b =>
                {
                    b.HasOne("Music_App.Models.Music", null)
                        .WithMany()
                        .HasForeignKey("MusicListTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Music_App.Models.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistsPlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
